name: Firebase PR Preview Deploy

on:
  pull_request:
    types: [labeled]

env:
  REACT_APP_CLOUDFLARE_APIKEY: ${{secrets.CLOUDFLARE_APIKEY}}

jobs:
  firebase-pr-preview:
    name: Firebase Development Deploy
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'create-live-preview')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup Node v14
        uses: actions/setup-node@master
        with:
          node-version: '14.x'

      - name: Create .env File
        run: |
          touch .env
          echo REACT_APP_CLOUDFLARE_APIKEY=$REACT_APP_CLOUDFLARE_APIKEY >> .env
          cat .env
          echo ${{secrets.FIREBASE_SERVICE_ACCOUNT}}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build React WebApp
        run: yarn build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: apti-che
          expires: 14d

      - name: removelabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: create-live-preview
          type: remove